# This file contains your private key.
# Do not give it away lightly!
Suite = "Ed25519"
Public = "a21aa21ccbc7818daac7bcffecb7e0d69d00f4747b83d895217e416c4fa185cc"
Private = "a58dd32e46a08639c70fc5a3cdf4383ffd927f0eeb577262d4ad835bc1b8ec0c"
Address = "tcp://localhost:7004"
ListenAddress = ""
Description = "Conode_2"
WebSocketTLSCertificate = ""
WebSocketTLSCertificateKey = ""
